=== erc-dharma/mdt-editor/templates/DHARMA_mdt_textDTD.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!-- Name of the file: according to the FNC of the project, it should be DHARMA_mdt_inscriptionID.xml and the inscriptionID comes from the tag <textID> -->
<!ELEMENT textMetadataTemplate (resourceManagement,textDescription)>
  <!ELEMENT resourceManagement (resourceID,metadataOrigin,metadataEditor,metadataContribution+,metadataReview+,project,corpus,metadataRights)>
  <!ELEMENT resourceID EMPTY>
  <!ATTLIST resourceID
  digitalID ID #REQUIRED
  >
    <!ELEMENT metadataOrigin (#PCDATA)>
    <!ELEMENT metadataEditor (creation+)>
      <!ELEMENT creation EMPTY>
      <!-- ajouter un pointeur vers la liste des membres du projet -->
      <!ATTLIST creation
      who CDATA #REQUIRED
      when CDATA #REQUIRED
      >
    <!ELEMENT metadataContribution (change)>
      <!ELEMENT change (#PCDATA)>
      <!-- ajouter un pointeur vers la liste des membres du projet -->
      <!ATTLIST change
      who CDATA #REQUIRED
      when CDATA #REQUIRED
      status  CDATA #REQUIRED
      ><!-- ajouter les valeurs possibles pour le workflow -->
    <!ELEMENT metadataReview EMPTY>
    <!-- ajouter un pointeur vers la liste des membres du projet -->
    <!ATTLIST metadataReview
    who CDATA #REQUIRED
    when CDATA #REQUIRED
    >
    <!ELEMENT project (#PCDATA)>
    <!ELEMENT corpus (#PCDATA)>
    <!ELEMENT metadataRights EMPTY>
    <!ATTLIST metadataRights
    target CDATA #FIXED "CC0 1.0"
    >
<!ELEMENT textDescription (textID,alternativeID,textDesignation,alternativeDesignation,textTypeLevel1+,textTypeLevel2+,textTypeLevel3+,textTypeLevel4+,linesNumber,textLanguage+,textScriptClassificationLevel1+,textScriptClassificationLevel2+,textScriptClassificationLevel3,textScriptMaturity+,textDate,origDate,textFiliation,textSummary,keywords,textRemarks,textBibliography,textRights,relatedResources)>
<!-- PRECISER LES CHAMPS OBLIGATOIRES OU OPTIONNELS -->
  <!ELEMENT textID EMPTY>
  <!ATTLIST textID
  idno ID #REQUIRED
  >
  <!ELEMENT alternativeID (#PCDATA)>
  <!ELEMENT textDesignation (#PCDATA)>
  <!ELEMENT alternativeDesignation (#PCDATA)>
  <!ELEMENT textTypeLevel1 EMPTY>
  <!ATTLIST textTypeLevel1
  value (unknown_text_type|administrative/legal|commemorative|donative|inaugurative|literary|miscellaneous|magical/religious/moral|utilitarian) "unknown_text_type"
  >
  <!ELEMENT textTypeLevel2 EMPTY>
  <!ATTLIST textTypeLevel2
  value (unknown_text_type|agreement_between_civil_parties|agreement_between_rulers|royal_order|eulogy|religious_grant_of_mobile_assets|religious_land_grant|secular_donation|construction_of_public_utility|construction_of_religious_building|installation_of_architectural_element|installation_of_religious_image|renovation|literary_citation|devotional|merit_transfer|moral/religious_instruction/exhortation|religious_citation|ritual/magical_formula|siddhayatra|date|designation_of_community|designation_of_office|label|name_of_deity|name_of_person|topographic) "unknown_text_type"
  >
  <!ELEMENT textTypeLevel3 EMPTY>
  <!ATTLIST textTypeLevel3
  value (unknown_text_type|debt_clearance|sale_deed|resolution_of_dispute|tax_regulation|genealogy|memorial|victory_record|blank_land_grant|confirmation_of_previous_land_grant|land_sale_grant|pranidhana|curse/spell|mantra/dharani|chronogram|artwork_label) "unknown_text_type"
  >
  <!ELEMENT textTypeLevel4 EMPTY>
  <!ATTLIST textTypeLevel4
  value (unknown_text_type|hero_memorial|sati_memorial|pratitya-samutpada) "unknown_text_type"
  >
  <!ELEMENT linesNumber (#PCDATA)>
  <!ELEMENT textLanguage EMPTY>
  <!ATTLIST textLanguage
  value (unknown|Tamil|Sanskrit) "unknown"
  ><!-- ajouter les valeurs des vocabulaires contrôlés d'OpenTheso -->
  <!ELEMENT textScriptClassificationLevel1 EMPTY>
  <!ATTLIST textScriptClassificationLevel1
 value (unknown|brahmi_and_derivatives|kharosthi|arabic_script|chinese_script) "unknown"
  >
  <!ELEMENT textScriptClassificationLevel2 EMPTY>
  <!ATTLIST textScriptClassificationLevel2
 value (unknown|northern_class_brahmi|southern_class_brahmi|southeast_asian_brahmi|jawi_script) "unknown"
  ><!ELEMENT textScriptClassificationLevel3 EMPTY>
  <!ATTLIST textScriptClassificationLevel3
 value (unknown|siddhamatrika|gaudi|nagari|tamil_script|grantha|vatteluttu|khmer_script|cam_script|mon-burmese_script|pyu_script|kawi_script|batak_script|balinese_script|sundanese_script|old_west_javanese_script) "unknown"
  >
  <!ELEMENT textScriptMaturity EMPTY>
  <!ATTLIST textScriptMaturity
 value (unknown|early_brahmi|middle_brahmi|late_brahmi|regional_brahmi-derived_script|vernacular_brahmi-derived_script) "unknown"
  >
  <!ELEMENT textDate (dateRegnalYear,date,dateJovianCycle,origDate)>
    <!ELEMENT dateRegnalYear (ruler,year*,month*,fortnight*,day*,remark*)>
      <!ELEMENT ruler (#PCDATA)>
      <!ELEMENT year (#PCDATA)>
      <!ELEMENT month (#PCDATA)>
      <!ELEMENT fortnight (#PCDATA)>
      <!ELEMENT day (#PCDATA)>
      <!ELEMENT remark (#PCDATA)>
    <!ELEMENT date (year,month,fornight,day,remark)>
    <!ATTLIST date
    calendar (Saka|Gupta|Valabhi|Vikrama|Burmese|Sanjaya|Other|Unknown) "Saka"
    ><!-- liste à revoir -->
      <!--<!ELEMENT year (#PCDATA)>
      <!ELEMENT month (#PCDATA)>
      <!ELEMENT fortnight (#PCDATA)>
      <!ELEMENT day (#PCDATA)>-->
    <!ELEMENT dateJovianCycle (cycleName,month,fortnight,day,remark)>
      <!ELEMENT cycleName (#PCDATA)>
      <!--<!ELEMENT month (#PCDATA)>
      <!ELEMENT fortnight (#PCDATA)>
      <!ELEMENT day (#PCDATA)>-->
    <!ELEMENT origDate (#PCDATA)>
    <!ATTLIST origDate
    notBefore CDATA #REQUIRED
    notAfter CDATA #REQUIRED
    when CDATA #REQUIRED
    precision (low|medium|high) "low"
    evidence (internal_date|lettering|nomenclature|prosopography|reign|titulature|context)
    datingMethod #FIXED "gregorian"
    > <!-- liste à définir -->
  <!ELEMENT textFiliation (duplicateText,reissue)>
    <!ELEMENT duplicateText (duplicateTextID+)>
      <!ELEMENT duplicateTextID (ID,corpus,reference)>
        <!ELEMENT ID (#PCDATA)>
        <!ELEMENT corpus (#PCDATA)>
        <!ELEMENT reference (#PCDATA)>
        <!-- the ID of the duplicate can be added as free text, but it needs the name of the project and the reference (publication or url if it's online) -->
    <!ELEMENT reissue (textReissue,reissueTextID,reissueDate)>
      <!ELEMENT textReissue EMPTY>
      <!ATTLIST textReissue
      value (yes|no) "no"
      ><!-- not sure of that -->
      <!ELEMENT reissueTextID (ID,corpus,reference)>
        <!ELEMENT ID (#PCDATA)>
        <!ELEMENT corpus (#PCDATA)>
        <!ELEMENT reference (#PCDATA)>
        <!-- the ID of the duplicate can be added as free text, but it needs the name of the project and the reference (publication or url if it's online) -->
      <!ELEMENT reissueDate EMPTY>
      <!ATTLIST reissueDate
      when CDATA #IMPLIED
      ><!-- not sure of that -->
  <!ELEMENT textSummary (p)>
    <!ELEMENT p (#PCDATA)>
  <!ELEMENT keywords (term+)>
    <!ELEMENT term (#PCDATA)>
  <!ELEMENT textRemarks (p)>
   <!-- <!ELEMENT p (#PCDATA)>-->
  <!ELEMENT textRights (publicationProject,textDistributionRights)>
    <!ELEMENT publicationProject (#PCDATA)>
    <!ELEMENT textDistributionRights (p)>
    <!ATTLIST textDistributionRights
    target (CC_BY_4.0|other) "CC BY 4.0"
    ><!-- dans l'élément p, on déclare l'auteur des métadonnées que l'on cite. Si le texte est établi par DHARMA sans citation, la licence CC BY 4.0 s'applique -->
  <!ELEMENT relatedResources (artefactID+,surrogateID+,imageID+)>
    <!ELEMENT artefactID EMPTY>
    <!ATTLIST artefactID
    idno ID #REQUIRED
    >
    <!ELEMENT surrogateID EMPTY>
    <!ATTLIST surrogateID
    idno ID #REQUIRED
    >
    <!ELEMENT imageID EMPTY>
    <!ATTLIST imageID
    idno ID #REQUIRED
    >

=== erc-dharma/mdt-editor/templates/DHARMA_mdt_textTemplate_v01.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Name of the file: according to the FNC of the project, it should be DHARMA_mdt_inscriptionID.xml and the inscriptionID comes from the tag <textID> -->
<!DOCTYPE textMetadataTemplate SYSTEM "https://raw.githubusercontent.com/erc-dharma/project-documentation/master/schema/latest/DHARMA_mdt_textDTD.dtd">
<textMetadataTemplate xmlns="https://github.com/erc-dharma/mdt-editor">
<resourceManagement><!-- Description of the file -->
	<resourceID digitalID=""/><!-- DHARMA identifier of the text: The identifier must have the form INSCorpusDesignation#####, where the corpusDesignation is taken from 1.1 of the DHARMA Guide to File Naming, and ##### is a five-digit number with leading zeroes. If there is an established inventory, created independently of DHARMA, indicate here the standard citation form of the inventory number (examples: "K. 24", "C. 101", "EIAD 5", "IR 761") adapted to the DHARMA conventions (expamples: INSK00024, INSC00101, INSEIAD00005, INSIR00761) -->
	<metadataOrigin></metadataOrigin><!-- Origin of the metadata: database or publication -->
	<metadataEditor><!-- Edition of the metadata  -->
		<creation who="" when=""/><!-- Person(s) who edited metadata and date of the edition (YYYY-MM-DD). May be repeated -->
	</metadataEditor>
	<metadataContribution><!-- Modification of the metadata -->
		<change who="" when="" status=""></change><!-- Person(s) who modified to metadata edition, date of the modification (YYYY-MM-DD) and type of modification. May be repeated -->
	</metadataContribution>
	<metadataReview who="" when=""/><!-- Validation of the metadata: person(s) who reviewed metadata and date of the review (YYYY-MM-DD). May be repeated -->
	<project>DHARMA</project><!-- Project responsible for making these metadata available: DHARMA -->
	<corpus></corpus><!-- Corpus (or corpora) to which the inscription pertains -->
	<metadataRights target="CC0"/><!-- Licence applicable to metadata: CC0 -->
</resourceManagement>
<textDescription><!-- Description of the text -->
  <textID idno=""/><!-- DHARMA identifier of the text: The identifier must have the form INSCorpusDesignation#####, where the corpusDesignation is taken from 1.1 of the DHARMA Guide to File Naming, and ##### is a five-digit number with leading zeroes. If there is an established inventory, created independently of DHARMA, indicate here the standard citation form of the inventory number (examples: "K. 24", "C. 101", "EIAD 5", "IR 761") adapted to the DHARMA conventions (expamples: INSK00024, INSC00101, INSEIAD00005, INSIR00761). -->
	<alternativeID></alternativeID><!-- Other identifiers for the text that may be found in scholarly literature. May be repeated -->
	<textDesignation></textDesignation><!-- The title that will be or has been assigned to the inscription. For creating such titles, follow the recommendation of the Encoding Guide.  -->
	<alternativeDesignation></alternativeDesignation><!-- Other titles that have been assigned to the text in scholarly literature. May be repeated -->
  <textTypeLevel1 value=""/><!-- Choose the main term in the hierarchy to describe the category of text. May be repeated -->
	<textTypeLevel2 value=""/><!-- Choose the most precise term depending on the previous category you chose to describe the type of text. May be repeated -->
	<textTypeLevel3 value=""/><!-- Choose the most precise term depending on the previous category you chose to describe the type of text. May be repeated -->
	<textTypeLevel4 value=""/><!-- Choose the most precise term depending on the previous category you chose to describe the type of text. May be repeated -->
  <linesNumber></linesNumber><!-- Sum total of lines in the text, all surfaces combined. The number filled in here should be one that a machine can recognize. -->
	<textLanguage value=""/><!-- Choose the language of the text. May be repeated -->
	<textScript value=""/><!-- Choose the script of the text. May be repeated -->
	<textDate><!-- Description of the date of the text: describe here the date of the text according to the calendar (regnal year with the name of the ruler, Saka, Gupta, Valabhi, Vikrama, Burmese or Sanjaya calendar, Jovian cycle) and translate it in gregorian equivalence -->
	<dateRegnalYear><!-- Regnal date: fill in the name of the ruler and the specification of the month, fornight and day -->
		<ruler></ruler><!-- Name of the ruler -->
		<year></year><!-- Specification of the year -->
		<month></month><!-- Specification of the month -->
		<fortnight></fortnight><!-- Specification of the fortnight -->
		<day></day><!-- Specification of the day -->
		<remark></remark><!-- Remarks on the date -->
	</dateRegnalYear>
	<date calendar=""><!-- Before to declare the date, choose the calendar and then, fill in the specification of the year, month, fortnight and day. May be repeated -->
		<year></year><!-- Specification of the year -->
		<month></month><!-- Specification of the month -->
		<fortnight></fortnight><!-- Specification of the fortnight -->
		<day></day><!-- Specification of the day -->
		<remark></remark><!-- Remarks on the date -->
	</date>
	<dateJovianCycle>
		<cycleName></cycleName><!-- Name of the Jovian cycle -->
		<month></month><!-- Specification of the month -->
		<fortnight></fortnight><!-- Specification of the fortnight -->
		<day></day><!-- Specification of the day -->
		<remark></remark><!-- Remarks on the date -->
	</dateJovianCycle>
	<origDate notBefore="" notAfter="" when="" precision="" evidence="" datingMethod="gregorian"></origDate><!-- Equivalence of the date according to the gregorian calendar. Specify the precise date if known (when=YYYY-MM-DD) or the range (notBefore, notAfter), the precision of th datation (high, medium, low) and choose the evidence that makes you able to date the text. -->
	</textDate>
	<textFiliation>
		<duplicateText><!-- The text can be a duplicate of an other text. Fill in here the metadata of the duplicated text. May be repeated -->
		<duplicateTextID>
			<ID></ID><!-- Identifier of the duplicated text -->
			<corpus></corpus><!-- Corpus to which the duplicated text belongs -->
			<reference></reference><!-- Bibliographical reference of the duplicated text filled in according to the Zotero Guide -->
		</duplicateTextID>
		</duplicateText>
		<reissue><!-- The text can be a reissue of an other text. Fill in here the metadata of the reissued text. May be repeated -->
		<textReissue value=""/><!-- Select the value "yes" if the text is a reissue -->
		<reissueTextID>
			<ID></ID><!-- Identifier of the reissued text -->
			<corpus></corpus><!-- Corpus to which the reissued text belongs -->
			<reference></reference><!-- Bibliographical reference of the reissued text filled in according to the Zotero Guide -->
		</reissueTextID>
		<reissueDate when=""/><!-- Date of the reissue following the gregorian calendar, if it is different of the date of the text (YYYY-MM-DD) -->
	</reissue>
	</textFiliation>
  <textSummary><p></p></textSummary><!-- Summary of the text -->
	<keywords><!-- Add keywords to charaterize the description of the text. The choice of terms is free -->
		<term></term><!-- may be repeated -->
	</keywords>
	<textRemarks><p></p></textRemarks><!-- Remarks on the text -->
	<textRights>
		<publicationProject>DHARMA</publicationProject><!-- Project responsible for making this text edition available: DHARMA -->
		<textDistributionRights target="CC-BY"/><!-- Licence applicable to the text edition: CC-BY -->
	</textRights>
	<relatedResources>
		<artefactID idno=""/><!-- Identifier(s) of the related artefact(s). May be repeated -->
		<surrogateID idno=""/><!-- Identifier(s) of the related surrogate(s). May be repeated -->
		<imageID idno=""/><!-- Identifier(s) of the related image(s). May be repeated -->
	</relatedResources>
</textDescription>
</textMetadataTemplate>

=== erc-dharma/mdt-editor/templates/DHARMA_mdt_INSCIC00004_test.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE DHARMA_mdt_INSCIC00004_test SYSTEM "DHARMA_mdt_textDTD.dtd">
<textMetadataTemplate>
<resourceManagement>
	<resourceID digitalID=""/>
	<metadataOrigin>Corpus des inscriptions du Campa</metadataOrigin>
	<metadataEditor>
		<creation who="Arlo Griffiths" when=""/><!-- may be repeated -->
		<creation who="Amandine Lepoutre" when=""/>
	</metadataEditor>
	<metadataContribution>
		<change who="Adeline Levivier" when="2021-01-28" status="transforming in XML"></change><!-- may be repeated -->
	</metadataContribution>
	<metadataReview who="" when=""/><!-- may be repeated -->
	<project>DHARMA</project>
	<corpus>CIC</corpus>
	<metadataRights target="CC0 1.0"/>
</resourceManagement>
<textDescription>
  <textID idno="INSCIC00004"/>
	<alternativeID>C. 4</alternativeID><!-- may be repeated -->
	<textDesignation>Doorjamb from Phan Rang</textDesignation>
	<alternativeDesignation></alternativeDesignation><!-- may be repeated -->
  <textType value="donation"/><!-- may be repeated -->
  <linesNumber>41</linesNumber>
	<textLanguage value="Sanskrit"/><!-- may be repeated -->
	<textScript value="Kawi"/><!-- may be repeated -->
	<textDate>
	<dateRegnalYear>
		<ruler></ruler>
		<year></year>
		<month></month>
		<fortnight></fornight>
		<day></day>
		<remark></remark>
	</dateRegnalYear>
	<date calendar="Saka"><!-- may be repeated --><!-- the calendar has to be declared in the attribute calendar -->
		<year>1148</year>
		<month></month>
		<fortnight></fornight>
		<day></day>
		<remark></remark>
	</date>
	<dateJovianCycle>
		<cycleName></cycleName>
		<month></month>
		<fortnight></fornight>
		<day></day>
		<remark></remark>
	</dateJovianCycle>
	<origDate notBefore="1226" notAfter="1227" when="" precision="high" evidence="internal_date" datingMethod="gregorian">1226/7</origDate><!-- equivalence of the date according to the occidental calendar -->
	</textDate>
	<textFiliation>
		<duplicateText>
		<duplicateTextID>
			<ID></ID>
			<corpus></corpus>
			<reference></reference>
		</duplicateTextID><!-- may be repeated -->
		</duplicateText>
		<reissue>
		<textReissue value="no"/>
		<reissueTextID>
			<ID></ID>
			<corpus></corpus>
			<reference></reference>
		</reissueTextID><!-- may be repeated -->
		<reissueDate when=""/>
	</reissue>
	</textFiliation>
  <textSummary><p></p></textSummary>
	<keywords><!-- may be repeated -->
		<term></term>
	</keywords>
	<textRemarks><p></p></textRemarks>
	<textRights>
		<publicationProject>DHARMA</publicationProject>
		<textDistributionRights target="CC BY 4.0"/>
	</textRights>
	<relatedResources>
		<artefactID idno="ART000001"/><!-- may be repeated -->
		<surrogateID idno="SUR000001"/><!-- may be repeated -->
		<imageID idno="DHARMA_INSCIC00004_001.jpg"/><!-- may be repeated -->
	</relatedResources>
</textDescription>
</textMetadataTemplate>
